### ISSUE TITLE
Feature Request: Add native support for Kubernetes Secrets

### ISSUE THREAD

**Issue by jcjones87** [hashicorp/vault-k8s#185]
**Is your feature request related to a problem? Please describe.**
The current way of injecting files and environmental variables via the Agent Sidecar Injector overlaps with functionality built into Kubernetes. This feature would enable native support, which would improve Vault's integration into the Kubernetes ecosystem. IE - you'd like to run a stateless service with Knative, which uses a CRD to deploy the application.

**Describe the solution you'd like**
There are multiple ways to design it. There'll probably need to be a new controller or something. It could be implemented as a new CRD, which creates a Kubernetes Secret based on a role and one or more secrets in Vault. Or perhaps the config map functionality could be extended to output a secret. 

**Describe alternatives you've considered**
I'm using the Agent Sidecar Injector. It works, but I'm running into the limitation of the Agent being tied to a deployment.

**Comment by jasonodonnell** [comment]
Hi @jcjones87, thanks for the feature request.

We're working on another project, the Vault CSI Storage Provider, which will support syncing secrets to Kubernetes. This project is currently in alpha but we're actively working on getting this ready for GA. I would suggest following along on that project, we expect a lot of activity there soon: https://github.com/hashicorp/secrets-store-csi-driver-provider-vault

Since the injector doesn't communicate with Vault at all (only the injected Vault Agents do), the injector cannot support secret syncing. We're working on CSI specifically so we can support this use case without completely overhauling the injector.
