### ISSUE TITLE
Support for providing imagePullSecrets for the injected agent image

### ISSUE THREAD

**Issue by tl-eddie-hoffman** [hashicorp/vault-k8s#286]
**Is your feature request related to a problem? Please describe.**

With larger deployments Docker Hub will rate limit the pulling of images unless authenticated. To avoid this a secret  must be used to authenticate to avoid rate limiting. Without this pods fail to start if the rate limit is hit when unauthenticated and attempting to pull the `hashicorp/vault` docker image.

https://www.docker.com/increase-rate-limits

It is possible to configure the imagePullSecrets for the injector but not the actual agent image that is used for the init and sidecar container.

**Describe the solution you'd like**

An environment variable that can be passed to the injector with the secret name and this can therefore be set in the helm chart in order to specify the imagePullSecre for Docker Hub authentication. `.Values.global.imagePullSecrets` in the Helm chart could be used  for an `env` in the injector deployment. The injector would then inject this value into `imagePullSecrets` for the agent container configuration

**Describe alternatives you've considered**
None as Docker Hub authentication is required to avoid throttling.

**Comment by tvoran** [comment]
Hi @tl-eddie-hoffman, since `imagePullSecrets` is specified at the Pod level instead of per container, have you tried setting it in the Pod you submit? There's an example here: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod

Since Pods can only reference image pull secrets in their own namespace, setting that in an injector environment variable wouldn't really work since the injector works across namespaces. And if we were to add an annotation that specifies which pull secret to use on a Pod, that wouldn't be much different that specifying imagePullSecrets in the Pod manifest directly.

**Comment by tl-eddie-hoffman** [comment]
@tvoran we have the same docker hub secret in every namespace. 

But appreciate that it doesn't make sense injecting this as it's at the namespace level as different secret names may be used.
