### ISSUE TITLE
Annotation for error_on_missing_key

### ISSUE THREAD

**Issue by iusergii** [hashicorp/vault-k8s#295]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to set Vault Agent Template Config for [error_on_missing_key](https://www.vaultproject.io/docs/agent/template-config#interaction-between-exit_on_retry_failure-and-error_on_missing_key) parameters thru annotation. 

**Describe the solution you'd like**
Annotatio similar to [exit_on_retry_failure](https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-hashicorp-com-template-config-exit-on-retry-failure)

**Comment by tvoran** [comment]
Thanks @iusergii, this does seem like a good thing to add. Since it's a per-template setting, we'd probably want it to be implemented similar to [agent-inject-secret](https://developer.hashicorp.com/vault/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-inject-secret) and [agent-inject-template](https://developer.hashicorp.com/vault/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-inject-template), perhaps something like `error-on-missing-<name>`.

**Comment by justinas-b** [comment]
+1

**Comment by tvoran** [comment]
Added in #441
