### ISSUE TITLE
Injector missing the sidecar injection randomly

### ISSUE THREAD

**Issue by vijay-dcrust** [hashicorp/vault-k8s#301]
**Describe the bug**

I am running a bunch of services on EKS and deployed vault on the same EKS to have dynamic rds credentials. The secrets are injected through vault pod injector webhook. The problem I am facing is that randomly there are some pods created which dont have the vault-agent-init and vault-agent sidecar injected in them. 

Strangely we are in such situation frequently that one pod of a particular deployment is having secrets injected while other is not.

Not sure where to start the troubleshooting for it. Is there a problem with mutating webhook or sidecar injector that the secrets are missed.

**Comment by vijay-dcrust** [comment]
Hi @tvoran I found some tls related error which occur intermittently. 

2021/10/14 07:21:42 http: TLS handshake error from 10.118.40.247:47680: remote error: tls: bad certificate

I found this issue same as mentioned here.

https://github.com/hashicorp/vault-k8s/issues/141

This was supposed to resolve in vault 0.7.0 which is not. We are already running vault-k8s-0.9.0.

I tried self signed certificate for one of the vault cluster which seems to be helping.

Is the vault-k8s still not supporting auto tls.

**Comment by tvoran** [comment]
We made auto tls more robust in [vault-k8s 0.13.0](https://github.com/hashicorp/vault-k8s/blob/main/CHANGELOG.md#0130-september-15-2021) and [vault-helm 0.16.0](https://github.com/hashicorp/vault-helm/blob/main/CHANGELOG.md#0160-september-16th-2021), so you should try upgrading. Otherwise I'd suggest setting up cert-manager to manage the certs as described here: https://www.vaultproject.io/docs/platform/k8s/helm/examples/injector-tls-cert-manager

**Comment by apsega** [comment]
+1 for the issue. Facing the same problems running `0.13.1` version of injector.

**Comment by tvoran** [comment]
@vijay-dcrust Since it sounds like you were on an older version of the injector I'm going to go ahead and close this for now.

@apsega If you're still seeing problems please open a new issue with as much detail as you can provide. Also make sure you're setting the number of injector replicas in the chart, and not scaling them up manually since the chart does some setup to support auto-tls with multiple replicas.

**Comment by wim-de-groot** [comment]
I am running vault version 1.9.3 and vault-k8s version 0.14.2 and it is still occurring.

**Comment by karthickkulandaivelu** [comment]
I am running vault version 1.10.3 and vault-k8s version 0.16.1 and it is still occurring.
